### ISSUE TITLE
keyFile file resource fails due to nil name

### ISSUE THREAD

**Issue by shortdudey123** [sous-chefs/mongodb#116]
Bug found by @gsaslis and was introduced by my commit in https://github.com/sous-chefs/mongodb-cookbook/commit/68926426a39da13579aa739bb839615affbdc1e4

```
 ArgumentError
  -------------
  You must supply a name when declaring a file resource
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/mongodb/recipes/install.rb:87:in `from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    /var/chef/cache/cookbooks/mongodb/recipes/default.rb:22:in `from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    /var/chef/cache/cookbooks/db/recipes/default.rb:8:in `from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/mongodb/recipes/install.rb:
  
   80:      options packager_opts
   81:      action :install
   82:      version node['mongodb']['package_version']
   83:    end
   84:  end
   85:  
   86:  # Create keyFile if specified
   87>> file node['mongodb']['config']['keyFile'] do
   88:    owner node['mongodb']['user']
   89:    group node['mongodb']['group']
   90:    mode  '0600'
   91:    backup false
   92:    content node['mongodb']['key_file_content']
   93:    only_if { node['mongodb']['key_file_content'] }
   94:  end
   95:  
  
  Platform:
  ---------
  x86_64-linux
  
  
  Running handlers:
[2016-11-21T05:25:27+00:00] ERROR: Running exception handlers
    - Chef::Handler::Slack
  Running handlers complete
[2016-11-21T05:25:27+00:00] ERROR: Exception handlers complete
  Chef Client failed. 3 resources updated in 11 seconds
[2016-11-21T05:25:27+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-11-21T05:25:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-11-21T05:25:27+00:00] ERROR: You must supply a name when declaring a file resource
[2016-11-21T05:25:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Fails since `node['mongodb']['config']['keyFile']` is only initialized if `node['mongodb']['key_file_content']` is not `nil`

**Comment by shortdudey123** [comment]
Completed in v1 rewrite
