### ISSUE TITLE
Error starting service on Ubuntu 16.04 (xenial64) 

### ISSUE THREAD

**Issue by gigo6000** [sous-chefs/mongodb#132]
I'm using this box in Vagrant:

```
   8   # box
   9   config.vm.box = 'ubuntu/xenial64'
```

And here's the error:

```
==> default: * service[mongodb] action enable
==> default: [2017-03-06T14:05:59+00:00] ERROR: service[mongodb] (mongodb::default line 202) had an error: Errno::ENOENT: No such file or directory - /sbin/status; ignore_failure is set, continuing
==> default: 
==> default:     
==> default:     
==> default: ================================================================================
==> default:     Error executing action `enable` on resource 'service[mongodb]'
==> default:     ================================================================================
==> default:     
==> default: 
==> default:     
==> default: Errno::ENOENT
==> default:     -------------
==> default:     
==> default: No such file or directory - /sbin/status
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Resource Declaration:
==> default: 
==> default:     ---------------------
==> default:     
==> default: # In /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb
==> default:     
==> default: 
==> default:     202:   service new_resource.name do
==> default:     203:     provider Chef::Provider::Service::Upstart if node['mongodb']['apt_repo'] == 'ubuntu-upstart'
==> default:     204:     supports :status => true, :restart => true
==> default:     205:     action new_resource.service_action
==> default:     206:     new_resource.service_notifies.each do |service_notify|
==> default:     207:       notifies :run, service_notify
==> default: 
==> default:     
==> default: 208:     end
==> default:     209:     notifies :create, 'ruby_block[config_replicaset]', :immediately if new_resource.is_replicaset && new_resource.auto_configure_replicaset
==> default:     
==> default: 210:     notifies :create, 'ruby_block[config_sharding]', :immediately if new_resource.is_mongos && new_resource.auto_configure_sharding
==> default:     211:       # we don't care about a running mongodb service in these cases, all we need is stopping it
==> default:     212:     ignore_failure true if new_resource.name == 'mongodb'
==> default:     
==> default: 213:   end
==> default:     
==> default: 214: 
==> default:     215:   # replicaset
==> default:     216:   if new_resource.is_replicaset && new_resource.auto_configure_replicaset
==> default:     217:     rs_nodes = search(
==> default:     218:       :node,
==> default:     
==> default: 219:       "mongodb_cluster_name:#{new_resource.replicaset['mongodb']['cluster_name']} AND \
==> default:     220:        mongodb_is_replicaset:true AND \
==> default:     
==> default: 221:        mongodb_shard_name:#{new_resource.replicaset['mongodb']['shard_name']} AND \
==> default:     
==> default: 222:        chef_environment:#{new_resource.replicaset.chef_environment}"
==> default:     223:     )
==> default:     224: 
==> default:     225:     ruby_block 'config_replicaset' do
==> default:     
==> default: 226:       block do
==> default:     227:         MongoDB.configure_replicaset(new_resource.replicaset, replicaset_name, rs_nodes) unless new_resource.replicaset.nil?
==> default:     
==> default: 228:       end
==> default:     
==> default: 229:       action :nothing
==> default:     230:     end
==> default:     231: 
==> default:     232:     ruby_block 'run_config_replicaset' do
==> default: 
==> default:     233:       block {}
==> default:     234:       notifies :create, 'ruby_block[config_replicaset]'
==> default:     
==> default: 235:     end
==> default:     
==> default: 236:   end
==> default:     237: 
==> default:     
==> default: 
==> default:     Compiled Resource:
==> default:     
==> default: ------------------
==> default:     
==> default: # Declared in /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:202:in `block in from_file'
==> default:     
==> default:     service("mongodb") do
==> default:       params {:mongodb_type=>"mongod", :action=>[:enable, :start], :logpath=>"/var/log/mongodb/mongodb.log", :dbpath=>"/data", :configservers=>[], :replicaset=>nil, :notifies=>[], :bind_ip=>"0.0.0.0", :port=>27017, :enable_rest=>false, :smallfiles=>false, :name=>"mongodb"}
==> default:       provider Chef::Provider::Service::Upstart
==> default:       action [:enable, :start]
==> default:       supports {:status=>true, :restart=>true}
==> default:     
==> default:   ignore_failure true
==> default:     
==> default:   retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:     
==> default:   service_name "mongodb"
==> default:     
==> default:   enabled nil
==> default:       running nil
==> default:       masked nil
==> default: 
==> default:       pattern "mongodb"
==> default:     
==> default:   declared_type :service
==> default:     
==> default:   cookbook_name "mongodb"
==> default:       recipe_name "default"
==> default:     end
==> default: 
==> default:     
==> default: 
==> default:     
==> default: Platform:
==> default: 
==> default:     
==> default: ---------
==> default:     
==> default: x86_64-linux
==> default:     
==> default: 
==> default:   * service[mongodb] action start
==> default: [2017-03-06T14:05:59+00:00] ERROR: service[mongodb] (mongodb::default line 202) had an error: Errno::ENOENT: No such file or directory - /sbin/status; ignore_failure is set, continuing
==> default: 
==> default:     
==> default:     
==> default: ================================================================================
==> default:     Error executing action `start` on resource 'service[mongodb]'
==> default:     
==> default: ================================================================================
==> default:     
==> default: 
==> default:     
==> default: Errno::ENOENT
==> default:     
==> default: -------------
==> default:     No such file or directory - /sbin/status
==> default:     
==> default:     
==> default: Resource Declaration:
==> default:     ---------------------
==> default:     
==> default: # In /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb
==> default:     
==> default:     
==> default: 202:   service new_resource.name do
==> default: 
==> default:     203:     provider Chef::Provider::Service::Upstart if node['mongodb']['apt_repo'] == 'ubuntu-upstart'
==> default:     204:     supports :status => true, :restart => true
==> default:     
==> default: 205:     action new_resource.service_action
==> default:     206:     new_resource.service_notifies.each do |service_notify|
==> default:     
==> default: 207:       notifies :run, service_notify
==> default:     
==> default: 208:     end
==> default:     209:     notifies :create, 'ruby_block[config_replicaset]', :immediately if new_resource.is_replicaset && new_resource.auto_configure_replicaset
==> default:     
==> default: 210:     notifies :create, 'ruby_block[config_sharding]', :immediately if new_resource.is_mongos && new_resource.auto_configure_sharding
==> default:     211:       # we don't care about a running mongodb service in these cases, all we need is stopping it
==> default:     
==> default: 212:     ignore_failure true if new_resource.name == 'mongodb'
==> default:     
==> default: 213:   end
==> default:     214: 
==> default:     
==> default: 215:   # replicaset
==> default:     216:   if new_resource.is_replicaset && new_resource.auto_configure_replicaset
==> default:     
==> default: 217:     rs_nodes = search(
==> default:     218:       :node,
==> default:     
==> default: 219:       "mongodb_cluster_name:#{new_resource.replicaset['mongodb']['cluster_name']} AND \
==> default:     220:        mongodb_is_replicaset:true AND \
==> default:     
==> default: 221:        mongodb_shard_name:#{new_resource.replicaset['mongodb']['shard_name']} AND \
==> default:     222:        chef_environment:#{new_resource.replicaset.chef_environment}"
==> default:     223:     )
==> default:     
==> default: 224: 
==> default:     225:     ruby_block 'config_replicaset' do
==> default:     
==> default: 226:       block do
==> default:     227:         MongoDB.configure_replicaset(new_resource.replicaset, replicaset_name, rs_nodes) unless new_resource.replicaset.nil?
==> default:     228:       end
==> default:     
==> default: 229:       action :nothing
==> default:     230:     end
==> default:     231: 
==> default: 
==> default:     
==> default: 232:     ruby_block 'run_config_replicaset' do
==> default:     233:       block {}
==> default:     234:       notifies :create, 'ruby_block[config_replicaset]'
==> default: 
==> default:     235:     end
==> default:     236:   end
==> default: 
==> default:     237: 
==> default: 
==> default:     
==> default: 
==> default:     
==> default: Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:202:in `block in from_file'
==> default:     
==> default:     
==> default: service("mongodb") do
==> default:     
==> default:   params {:mongodb_type=>"mongod", :action=>[:enable, :start], :logpath=>"/var/log/mongodb/mongodb.log", :dbpath=>"/data", :configservers=>[], :replicaset=>nil, :notifies=>[], :bind_ip=>"0.0.0.0", :port=>27017, :enable_rest=>false, :smallfiles=>false, :name=>"mongodb"}
==> default:       provider Chef::Provider::Service::Upstart
==> default:     
==> default:   action [:enable, :start]
==> default:     
==> default:   supports {:status=>true, :restart=>true}
==> default: 
==> default:       ignore_failure true
==> default:       retries 0
==> default:     
==> default:   retry_delay 2
==> default:     
==> default:   default_guard_interpreter :default
==> default:     
==> default:   service_name "mongodb"
==> default:       enabled nil
==> default:       running nil
==> default:     
==> default:   masked nil
==> default:       pattern "mongodb"
==> default:     
==> default:   declared_type :service
==> default: 
==> default:     
==> default:   cookbook_name "mongodb"
==> default:     
==> default:   recipe_name "default"
==> default:     end
==> default:     
==> default: 
==> default: 
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:     
```

Fix here: https://github.com/sous-chefs/mongodb/pull/131

**Comment by damacus** [comment]
Closing as unsupported. This targets Ubuntu 16.04, which is EOL and no longer part of the supported test matrix. The cookbook has since moved to the supported custom-resource implementation in #336; please open a fresh issue if a supported platform still fails.
