### ISSUE TITLE
Error executing action `run` on resource 'ruby_block[config_replicaset]'

### ISSUE THREAD

**Issue by heaven** [sous-chefs/mongodb#184]
```
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/sc-mongodb/libraries/mongodb.rb:74:in `configure_replicaset'
    /var/chef/cache/cookbooks/sc-mongodb/definitions/mongodb.rb:246:in `block (3 levels) in from_file'
```

Looking at the source I see it approaches
`node['mongodb']['config']['net']['port']` 
but should be 
`node['mongodb']['config']['mongod']['net']['port']`

**Comment by mike-stewart** [comment]
I'm getting the same problem. Seems that attribute is undefined by default.

**Comment by devsibwarra** [comment]
Looks like this was fixed in #186 already

**Comment by damacus** [comment]
Closing due to age and lack of current reproduction details. The legacy ruby_block/replicaset flow was removed by #336. Please open a fresh issue with current resource usage and logs if replica-set configuration still fails.
