### ISSUE TITLE
Replicaset Recipe Fails:  "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by Bernard2324** [sous-chefs/mongodb#197]
Self explanatory, I'm trying to build a mongodb replicaset between three hosts.  While trying to Chef the first host, I receive this error.  I could not find any documentation for correct use; is there any guidance?

`Recipe: sc-mongodb::replicaset
  * ruby_block[config_replicaset] action run

    ================================================================================
    Error executing action `run` on resource 'ruby_block[config_replicaset]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/sc-mongodb/libraries/mongodb.rb:74:in `configure_replicaset'
    /var/chef/cache/cookbooks/sc-mongodb/definitions/mongodb.rb:246:in `block (3 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/sc-mongodb/definitions/mongodb.rb

    244:     ruby_block 'config_replicaset' do
    245:       block do
    246:         MongoDB.configure_replicaset(node, replicaset_name, rs_nodes) unless new_resource.replicaset.nil?
    247:       end
    248:       action :nothing
    249:     end
    250:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/sc-mongodb/definitions/mongodb.rb:244:in `block in from_file'

    ruby_block("config_replicaset") do
      params {:mongodb_type=>"mongod", :action=>[:enable, :start], :logpath=>"/var/log/mongodb/mongod.log", :configservers=>[], :replicaset=>true, :notifies=>[], :not_if=>[], :name=>"mongod"}
      action [:nothing]
      default_guard_interpreter :default
      block_name "config_replicaset"
      declared_type :ruby_block
      cookbook_name "sc-mongodb"
      recipe_name "replicaset"
      block #<Proc:0x00000000021f60b0@/var/chef/cache/cookbooks/sc-mongodb/definitions/mongodb.rb:245>
    end

    System Info:
    ------------
    chef_version=13.9.1
    platform=centos
    platform_version=7.5.1804
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    program_name=chef-client worker: ppid=11384;start=16:16:16;
    executable=/opt/chef/bin/chef-client
`

**Comment by Bernard2324** [comment]
Nevermind, this was fixed in #186
