### ISSUE TITLE
E: Version '3.6.6' for 'mongodb-org' was not found

### ISSUE THREAD

**Issue by stavxyz** [sous-chefs/mongodb#276]
## :ghost: Brief Description

```
Error executing action `install` on resource 'apt_package[mongodb-org]'
...
E: Version '3.6.6' for 'mongodb-org' was not found
```

## :pancakes: Cookbook version

4.1.0

## :woman_cook:  Chef-Infra Version

16.10.7

## :tophat: Platform details

```
    System Info:
    ------------
    chef_version=16.10.17
    platform=ubuntu
    platform_version=18.04
    ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client
```

## Steps To Reproduce

Run `chef install`, `chef export ---archive` and then `chef-client --local-mode`

Policyfile:

```
name 'mongodb'
default_source :supermarket
cookbook 'sc-mongodb', '~> 4.1.0', :supermarket
run_list 'sc-mongodb::default'
```

## :police_car: Expected behavior

Expects version '3.6.6' for 'mongodb-org' to be installed or a different  version which is available should be specified by default.

## :heavy_plus_sign: Additional context

```
    ================================================================================
    Error executing action `install` on resource 'apt_package[mongodb-org]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '100'
    ---- Begin output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] ----
    STDOUT: Reading package lists...
    Building dependency tree...
    Reading state information...
    STDERR: W: --force-yes is deprecated, use one of the options starting with --allow instead.
    E: Version '3.6.6' for 'mongodb-org' was not found
    ---- End output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] ----
    Ran ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] returned 100

    Resource Declaration:
    ---------------------
    # In /var/chef/policy/mongodb/src/.chef/local-mode-cache/cache/cookbooks/sc-mongodb/recipes/install.rb

    114: package node['mongodb']['package_name'] do
    115:   options node['mongodb']['packager_options']
    116:   action :install
    117:   version package_version
    118:   not_if { node['mongodb']['install_method'] == 'none' }
    119: end
    120:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/policy/mongodb/src/.chef/local-mode-cache/cache/cookbooks/sc-mongodb/recipes/install.rb:114:in `from_file'

    apt_package("mongodb-org") do
      package_name "mongodb-org"
      action [:install]
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "sc-mongodb"
      recipe_name "install"
      options ["-o", "Dpkg::Options::=--force-confold", "--force-yes"]
      version "3.6.6"
      not_if { #code block }
    end

    System Info:
    ------------
    chef_version=16.10.17
    platform=ubuntu
    platform_version=18.04
    ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client

[2021-03-13T03:29:16+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2021-03-13T03:29:16+00:00] ERROR: Running exception handlers
Running handlers complete
[2021-03-13T03:29:16+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 15 resources updated in 01 minutes 44 seconds
[2021-03-13T03:29:16+00:00] FATAL: Stacktrace dumped to /var/chef/policy/mongodb/src/.chef/local-mode-cache/cache/chef-stacktrace.out
[2021-03-13T03:29:16+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-03-13T03:29:16+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: apt_package[mongodb-org] (sc-mongodb::install line 114) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
STDERR: W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Version '3.6.6' for 'mongodb-org' was not found
---- End output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] ----
Ran ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] returned 100
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:287:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package/deb.rb:114:in `run_noninteractive'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package/apt.rb:96:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:120:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:267:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:119:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:265:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:118:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:276:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:217:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:599:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:626:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:598:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:687:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:682:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:682:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:706:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application/base.rb:337:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.10.17/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:146:in `load'
/usr/bin/chef-client:146:in `<main>'

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
STDERR: W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Version '3.6.6' for 'mongodb-org' was not found
---- End output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] ----
Ran ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] returned 100
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:287:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package/deb.rb:114:in `run_noninteractive'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package/apt.rb:96:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:120:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:267:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:119:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:265:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:118:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:276:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:217:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:599:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:626:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:598:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:687:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:682:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:682:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:706:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application/base.rb:337:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.10.17/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:146:in `load'
/usr/bin/chef-client:146:in `<main>'
[2021-03-13T03:29:16+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: apt_package[mongodb-org] (sc-mongodb::install line 114) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
STDERR: W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Version '3.6.6' for 'mongodb-org' was not found
---- End output of ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] ----
Ran ["apt-get", "-q", "-y", "--allow-downgrades", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-org=3.6.6"] returned 100
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:287:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package/deb.rb:114:in `run_noninteractive'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package/apt.rb:96:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:120:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:267:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:119:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:265:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider/package.rb:118:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:276:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/provider.rb:217:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:599:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:626:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource.rb:598:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:687:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:682:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:682:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:706:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application/base.rb:337:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.10.17/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:146:in `load'
/usr/bin/chef-client:146:in `<main>'
```

**Comment by mehagar** [comment]
Looks like Mongo 3.6 is only supported on Ubuntu 18 starting from `3.6.20`+: https://docs.mongodb.com/v3.6/administration/production-notes/#supported-platforms

**Comment by damacus** [comment]
Closing as unsupported. This targets old MongoDB package availability for an unsupported/EOL matrix rather than a current cookbook defect. The cookbook has since moved to the supported custom-resource implementation in #336; please open a fresh issue with a supported OS, MongoDB, and Chef matrix if this still reproduces.
